package install

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"regexp"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/dafrie/kelson/internal/clusterprofile"
)

// The flux-aio row (issue #226, ADR-0030) and the four things that must stay
// true about it.
//
// It is the one catalog row whose bytes kelson ships rather than fetches, which
// is a real exception to ADR-0021's "nothing is vendored" rule. What earns the
// exception is that the snapshot is a mechanically reproducible build artifact
// rather than a copy somebody pasted in, and every clause of that sentence is
// enforced here rather than asserted:
//
//   - the committed bytes are the bytes the pin describes, so nobody can edit
//     the YAML to make something pass ([TestRenderedSnapshotMatchesThePin]);
//   - the render script and the pins table agree about which upstream module
//     produced them, so the two halves of the provenance cannot drift apart
//     ([TestRenderScriptAgreesWithThePins]);
//   - the Flux it installs is inside the minor the rest of the product is built
//     against ([TestRenderedRowPinsTheFluxTheProductInstalls]);
//   - a build WITHOUT the snapshot refuses loudly and leaves the cluster a
//     working alternative, rather than installing nothing and saying nothing
//     ([TestMissingSnapshotIsARefusalNotASilentSkip],
//     [TestSweepFallsBackToFluxOperatorWithoutASnapshot]).
//
// All of it runs in plain `go test ./...` with no network and no cluster, which
// is the point: the snapshot is generated by a script that needs ghcr.io, and
// the discipline around it must not.

// fluxAIOFixture is a flux-aio-shaped snapshot: the namespace, the two CRDs the
// delivery spine applies, and the single Deployment that is the whole of
// flux-aio's runtime. It stands in for upstream's real render, which is several
// hundred kilobytes of CRD schema that no unit test should carry and no
// reviewer would read.
const fluxAIOFixture = `# flux-aio 2.9.4-0 — every Flux controller in one pod.
#
# GENERATED FILE. DO NOT EDIT.
---
# Namespace/flux-system
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
# CustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kustomizations.kustomize.toolkit.fluxcd.io
spec:
  group: kustomize.toolkit.fluxcd.io
  names:
    kind: Kustomization
    plural: kustomizations
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
# CustomResourceDefinition/ocirepositories.source.toolkit.fluxcd.io
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ocirepositories.source.toolkit.fluxcd.io
spec:
  group: source.toolkit.fluxcd.io
  names:
    kind: OCIRepository
    plural: ocirepositories
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
---
# ServiceAccount/flux-system/flux
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: flux-system
---
# Deployment/flux-system/flux
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux-system
spec:
  template:
    spec:
      serviceAccountName: flux
      containers:
        - name: source-controller
        - name: kustomize-controller
        - name: helm-controller
        - name: notification-controller
`

// renderedFixture builds a Rendered Component row over a snapshot the test
// supplies, and swaps the embedded filesystem for the duration of the test.
//
// The digest is computed from the fixture rather than hard-coded, so these
// tests exercise the verification path without pinning a value that would have
// to be edited every time the fixture gains a line.
func renderedFixture(t *testing.T, name, namespace, profileField, body string) Component {
	t.Helper()
	path := "rendered/" + name + ".yaml"
	withRendered(t, map[string]string{path: body})
	return Component{
		Name:          name,
		Title:         name,
		Status:        StatusSupported,
		Version:       "v9.9.9",
		Rendered:      true,
		RenderedPath:  path,
		ModuleRef:     "oci://example.invalid/modules/" + name,
		ModuleVersion: "9.9.9-0",
		ModuleDigest:  digestOf([]byte("module-fixture")),
		SHA256:        digestOf([]byte(body)),
		Namespace:     namespace,
		ProfileField:  profileField,
		Provides:      "the fixture's capability",
	}
}

// withRendered swaps the embedded snapshot filesystem for one the test builds.
// Passing no files is how a test stands in for a build made before
// `make flux-aio` ever ran.
func withRendered(t *testing.T, files map[string]string) {
	t.Helper()
	mapped := fstest.MapFS{}
	for path, body := range files {
		mapped[path] = &fstest.MapFile{Data: []byte(body)}
	}
	original := renderedFS
	renderedFS = mapped
	t.Cleanup(func() { renderedFS = original })
}

// TestRenderedSnapshotMatchesThePin is the "cannot be hand-edited" half of
// ADR-0030 decision 2's argument, enforced rather than claimed — and it is
// deliberately written to be meaningful in BOTH worlds.
//
// A tree that carries the snapshot must carry a pin that digests it, or the
// bytes and the row describe different things. A tree that does not carry it
// must carry no pin at all, because a digest with nothing behind it reads like
// a working install to anyone skimming the table. Either state is legitimate;
// disagreement between them never is.
func TestRenderedSnapshotMatchesThePin(t *testing.T) {
	for _, c := range Components {
		if !c.Rendered {
			continue
		}
		t.Run(c.Name, func(t *testing.T) {
			body, ok := renderedSnapshot(c)
			if !ok {
				if c.SHA256 != "" {
					t.Fatalf("%s pins SHA256 %s and %s is absent from the binary: the row promises an "+
						"install this build cannot perform. Run `make flux-aio`, or clear the pin.",
						c.Name, c.SHA256, c.RenderedPath)
				}
				t.Skipf("no snapshot committed at %s, so this build refuses to install %s. That is a "+
					"legitimate state — the bytes are rendered at release time by hack/flux-aio-render.sh "+
					"(ADR-0030 decision 2) — but it is not a state to RELEASE from: "+
					".github/workflows/release.yml runs `hack/flux-aio-render.sh --check`, which fails until "+
					"the snapshot is generated and committed.", c.RenderedPath, c.Name)
			}
			sum := sha256.Sum256(body)
			if got := hex.EncodeToString(sum[:]); got != c.SHA256 {
				t.Fatalf("%s hashes to %s, want %s — the snapshot was edited by hand, or a pin was bumped "+
					"without running `make flux-aio`. These bytes are a build artifact: edit the pins, never "+
					"the file.", c.RenderedPath, got, c.SHA256)
			}
		})
	}
}

// TestRenderScriptAgreesWithThePins keeps the two halves of the provenance from
// drifting apart.
//
// hack/flux-aio-render.sh holds the pins that PRODUCE the snapshot; pins.go
// holds the pins that DESCRIBE it. Nothing but this test connects them, and a
// bumped script with an unbumped table would leave the row claiming a module
// version that no longer rendered it — provenance that reads correct and is
// false, which is worse than none. The check is a text scan rather than
// anything cleverer because the script must stay readable by a human as the
// reproducibility record, not become a config file for Go.
func TestRenderScriptAgreesWithThePins(t *testing.T) {
	c, ok := Lookup(FluxAIOName)
	if !ok {
		t.Fatal("the pins table has no flux-aio row")
	}
	const script = "../../../hack/flux-aio-render.sh"
	raw, err := os.ReadFile(script)
	if err != nil {
		t.Fatalf("reading %s: %v — the row's bytes have no reproducibility record without it", script, err)
	}
	body := string(raw)
	for _, want := range []struct{ assign, why string }{
		{`MODULE_REF="` + c.ModuleRef + `"`, "which module the bytes came from"},
		{`MODULE_VERSION="` + c.ModuleVersion + `"`, "which module version"},
		{`MODULE_DIGEST="sha256:` + c.ModuleDigest + `"`, "the exact upstream artifact, digest-pinned"},
		{`FLUX_VERSION="` + c.Version + `"`, "which Flux release the module packages"},
	} {
		if !strings.Contains(body, want.assign) {
			t.Errorf("%s does not set %s: the script and the pins table disagree about %s. Re-run "+
				"`make flux-aio` and paste the block it prints into pins.go.", script, want.assign, want.why)
		}
	}
	// The script writes where the row reads. A mismatch is a render that
	// succeeds and a build that still cannot install anything.
	if !strings.Contains(body, `OUT_FILE="$OUT_DIR/`+strings.TrimPrefix(c.RenderedPath, "rendered/")+`"`) {
		t.Errorf("%s does not write the file %s reads (%s)", script, c.Name, c.RenderedPath)
	}
	// The timoni pin lives in the script alone, by design (ADR-0030 decision 3
	// keeps timoni out of Go entirely) — but it must be an exact version with a
	// checksum beside it, or "pinned renderer" means nothing.
	if !regexp.MustCompile(`TIMONI_VERSION="v\d+\.\d+\.\d+"`).MatchString(body) {
		t.Error("hack/flux-aio-render.sh does not pin an exact timoni version; a patch bump is a different " +
			"renderer and therefore potentially different bytes")
	}
	if !regexp.MustCompile(`linux/amd64\) printf '%s' "[0-9a-f]{64}"`).MatchString(body) {
		t.Error("hack/flux-aio-render.sh has no checksum for the timoni binary it downloads")
	}
}

// TestRenderedRowPinsTheFluxTheProductInstalls: flux-aio is a packaging of the
// same controllers, so the Flux it installs has to be the Flux the rest of
// kelson is built against — the same rule hack/flux-crds.sh applies to the CRD
// fixtures the controller's envtest suite validates against.
func TestRenderedRowPinsTheFluxTheProductInstalls(t *testing.T) {
	c, ok := Lookup(FluxAIOName)
	if !ok {
		t.Fatal("the pins table has no flux-aio row")
	}
	minor := strings.TrimSuffix(FluxDistributionVersion, ".x")
	if !strings.HasPrefix(strings.TrimPrefix(c.Version, "v"), minor+".") {
		t.Fatalf("flux-aio pins Flux %s, outside FluxDistributionVersion %s. The two Flux rows would install "+
			"different minors, and the CRD schemas internal/controller validates against are the other one's.",
			c.Version, FluxDistributionVersion)
	}
	if c.Namespace != "flux-system" {
		t.Fatalf("flux-aio installs into %q; detection, the spine and flux-operator all assume flux-system",
			c.Namespace)
	}
}

// TestPlanDecodesTheCommittedSnapshot: a Rendered row reaches the cluster
// through exactly the same decode-and-stamp path as a fetched one, and fetches
// nothing.
func TestPlanDecodesTheCommittedSnapshot(t *testing.T) {
	c := renderedFixture(t, FluxAIOName, "flux-system", "flux", fluxAIOFixture)
	withComponents(t, c)
	fetcher := &fakeFetcher{}
	installer := newInstaller(t, newCluster(), fetcher)

	plan, err := installer.Plan(context.Background(), Request{Components: []string{FluxAIOName}})
	if err != nil {
		t.Fatalf("plan: %v", err)
	}
	if len(fetcher.asked) != 0 {
		t.Fatalf("fetched %v; a Rendered row's bytes are already in the binary", fetcher.asked)
	}
	if len(plan.Items) != 1 {
		t.Fatalf("items = %d, want 1", len(plan.Items))
	}
	item := plan.Items[0]
	if item.Digest != c.SHA256 {
		t.Fatalf("Digest = %q, want the snapshot digest %q: the preview must show what was verified",
			item.Digest, c.SHA256)
	}
	var got []string
	for _, o := range item.Objects {
		got = append(got, o.Ref.String())
		// Authored means "kelson composed this object". A rendered snapshot is
		// upstream's manifest, produced mechanically — the same standing a
		// fetched manifest has — so marking it Authored would tell a preview
		// reader kelson wrote a Deployment it did not write.
		if o.Authored {
			t.Fatalf("%s is marked Authored; these objects are upstream's, rendered, not composed", o.Ref)
		}
	}
	want := []string{
		"Namespace/flux-system",
		"CustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io",
		"CustomResourceDefinition/ocirepositories.source.toolkit.fluxcd.io",
		"ServiceAccount/flux-system/flux",
		"Deployment/flux-system/flux",
	}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("objects =\n  %v\nwant (in document order)\n  %v", got, want)
	}
}

// TestApplyStampsProvenanceOnRenderedObjects: ADR-0021 decision 3's per-object
// provenance is not weakened by the bytes coming from inside the binary.
// `kelson uninstall --component flux-aio` selects on exactly these labels.
func TestApplyStampsProvenanceOnRenderedObjects(t *testing.T) {
	c := renderedFixture(t, FluxAIOName, "flux-system", "flux", fluxAIOFixture)
	withComponents(t, c)
	cl := newCluster()
	installer := newInstaller(t, cl, &fakeFetcher{})

	plan, err := installer.Plan(context.Background(), Request{Components: []string{FluxAIOName}})
	if err != nil {
		t.Fatalf("plan: %v", err)
	}
	if _, err := installer.Execute(context.Background(), plan); err != nil {
		t.Fatalf("execute: %v", err)
	}
	dep := cl.get(t, "Deployment", "flux-system", "flux")
	if got := dep.GetLabels()[LabelComponent]; got != FluxAIOName {
		t.Fatalf("%s = %q, want %s — uninstall selects on this and nothing else", LabelComponent, got, FluxAIOName)
	}
	if got := dep.GetLabels()[LabelVersion]; got != c.Version {
		t.Fatalf("%s = %q, want %q: a cluster must be able to say which Flux it runs without reading this "+
			"repository", LabelVersion, got, c.Version)
	}
	if got := dep.GetAnnotations()[AnnOwnership]; got != OwnershipCreated {
		t.Fatalf("%s = %q, want %q", AnnOwnership, got, OwnershipCreated)
	}
}

// TestRenderedRowGetsNoFluxInstance: the FluxInstance belongs to flux-operator.
// flux-aio's snapshot IS the installation — there is no operator to hand a
// desired state to, and the FluxInstance CRD is not in the snapshot at all.
func TestRenderedRowGetsNoFluxInstance(t *testing.T) {
	c := renderedFixture(t, FluxAIOName, "flux-system", "flux", fluxAIOFixture)
	withComponents(t, c)
	installer := newInstaller(t, newCluster(), &fakeFetcher{})

	plan, err := installer.Plan(context.Background(), Request{Components: []string{FluxAIOName}})
	if err != nil {
		t.Fatalf("plan: %v", err)
	}
	for _, o := range plan.Items[0].Objects {
		if o.Ref.Kind == "FluxInstance" {
			t.Fatal("flux-aio planned a FluxInstance: nothing in its snapshot serves that CRD, so the apply " +
				"would fail after the Deployment was already in the cluster")
		}
	}
}

// TestSnapshotDigestMismatchRefusesBeforeApplying: a snapshot that is not the
// bytes the pin describes is not the thing this repository reviewed, and the
// check happens in the binary rather than only in CI so a tampered build
// refuses on the user's machine too.
func TestSnapshotDigestMismatchRefusesBeforeApplying(t *testing.T) {
	c := renderedFixture(t, FluxAIOName, "flux-system", "flux", fluxAIOFixture)
	c.SHA256 = digestOf([]byte("some other bytes entirely"))
	withComponents(t, c)
	cl := newCluster()
	installer := newInstaller(t, cl, &fakeFetcher{})

	_, err := installer.Plan(context.Background(), Request{Components: []string{FluxAIOName}})
	if err == nil {
		t.Fatal("a snapshot that does not match its pin was planned anyway")
	}
	if !strings.Contains(err.Error(), "does not match the pinned digest") {
		t.Fatalf("error %q does not say what is wrong", err)
	}
	if len(cl.applies) != 0 {
		t.Fatalf("applied %v; a digest mismatch must stop the plan before anything reaches the cluster",
			cl.applies)
	}
}

// TestMissingSnapshotIsARefusalNotASilentSkip: a build made before
// `make flux-aio` ran cannot install this row, and must say so. The failure
// mode this prevents is the quiet one — an install that reports success having
// applied nothing, on the one row a cluster's whole delivery path depends on.
func TestMissingSnapshotIsARefusalNotASilentSkip(t *testing.T) {
	c := renderedFixture(t, FluxAIOName, "flux-system", "flux", fluxAIOFixture)
	withRendered(t, nil) // a tree with no snapshot
	withComponents(t, c)
	installer := newInstaller(t, newCluster(), &fakeFetcher{})

	plan, err := installer.Plan(context.Background(), Request{Components: []string{FluxAIOName}})
	if err != nil {
		t.Fatalf("plan: %v", err)
	}
	if !plan.Empty() {
		t.Fatalf("plan has %d items for a component whose bytes this build does not carry", len(plan.Items))
	}
	if len(plan.Refusals) != 1 {
		t.Fatalf("refusals = %d, want 1: an install that can do nothing must say so", len(plan.Refusals))
	}
	r := plan.Refusals[0]
	if r.Outcome != clusterprofile.OutcomeNo {
		t.Fatalf("outcome = %v, want no: the component is genuinely absent, kelson just cannot supply it",
			r.Outcome)
	}
	if !strings.Contains(r.Reason, c.RenderedPath) {
		t.Fatalf("reason %q does not name the file that is missing", r.Reason)
	}
	if !strings.Contains(r.Remediation, "kelson install "+FluxOperatorName) {
		t.Fatalf("remediation %q does not offer the alternative that needs no snapshot — a cluster left with "+
			"no Flux at all is the worst outcome here", r.Remediation)
	}
}

// TestSweepPrefersFluxAIO is ADR-0030 decision 1 as a test: on a cluster with no
// Flux, `--all-missing` installs the one-pod distribution and declines
// flux-operator by name rather than installing both.
func TestSweepPrefersFluxAIO(t *testing.T) {
	aio := renderedFixture(t, FluxAIOName, "flux-system", "flux", fluxAIOFixture)
	operator, fetcher := pinnedFixture(FluxOperatorName, "flux-system", "flux", []byte(certManagerFixture))
	withComponents(t, aio, operator)
	installer := newInstaller(t, newCluster(), fetcher)

	plan, err := installer.Plan(context.Background(), Request{AllMissing: true})
	if err != nil {
		t.Fatalf("plan: %v", err)
	}
	if len(plan.Items) != 1 || plan.Items[0].Component.Name != FluxAIOName {
		var got []string
		for _, item := range plan.Items {
			got = append(got, item.Component.Name)
		}
		t.Fatalf("items = %v, want [%s] only: a sweep installs one Flux, and the default is the one-pod one",
			got, FluxAIOName)
	}
	if len(plan.Refusals) != 1 || plan.Refusals[0].Name != FluxOperatorName {
		t.Fatalf("refusals = %+v, want flux-operator declined by name", plan.Refusals)
	}
	r := plan.Refusals[0]
	if !strings.Contains(r.Reason, FluxAIOName) {
		t.Fatalf("reason %q does not say which Flux the sweep IS installing", r.Reason)
	}
	if !strings.Contains(r.Remediation, "kelson install "+FluxOperatorName) {
		t.Fatalf("remediation %q does not name the command that chooses full Flux", r.Remediation)
	}
	if !strings.Contains(r.Remediation, "previews") {
		t.Fatalf("remediation %q does not mention previews, the one feature that needs flux-operator "+
			"(ADR-0030 decision 4)", r.Remediation)
	}
	if len(fetcher.asked) != 0 {
		t.Fatalf("fetched %v; the declined row must not be downloaded", fetcher.asked)
	}
}

// TestSweepFallsBackToFluxOperatorWithoutASnapshot: the guard on the preference
// above. A build that cannot install flux-aio must not decline flux-operator in
// its favour — that would answer ADR-0028's "what if there is no Flux" with
// nothing at all, which is strictly worse than answering it with six
// Deployments.
func TestSweepFallsBackToFluxOperatorWithoutASnapshot(t *testing.T) {
	aio := renderedFixture(t, FluxAIOName, "flux-system", "flux", fluxAIOFixture)
	withRendered(t, nil)
	operator, fetcher := pinnedFixture(FluxOperatorName, "flux-system", "flux", []byte(certManagerFixture))
	withComponents(t, aio, operator)
	installer := newInstaller(t, newCluster(), fetcher)

	plan, err := installer.Plan(context.Background(), Request{AllMissing: true})
	if err != nil {
		t.Fatalf("plan: %v", err)
	}
	if len(plan.Items) != 1 || plan.Items[0].Component.Name != FluxOperatorName {
		var got []string
		for _, item := range plan.Items {
			got = append(got, item.Component.Name)
		}
		t.Fatalf("items = %v, want [%s]: with no flux-aio snapshot the sweep must still leave the cluster a "+
			"reconciler", got, FluxOperatorName)
	}
	// The missing snapshot is still reported. A sweep hides a refusal only when
	// the component is already present; "kelson cannot offer the default Flux"
	// is not that.
	if len(plan.Refusals) != 1 || plan.Refusals[0].Name != FluxAIOName {
		t.Fatalf("refusals = %+v, want the flux-aio row reported as unavailable", plan.Refusals)
	}
}

// TestNamingBothFluxRowsIsRefused: each row installs a complete set of Flux
// controllers, so a cluster given both would have two reconcilers watching the
// same CRDs. Detection says No to both — neither is individually wrong — so the
// refusal has to come from the request's own shape.
func TestNamingBothFluxRowsIsRefused(t *testing.T) {
	req := Request{Components: []string{FluxAIOName, FluxOperatorName}}
	err := req.Validate()
	if err == nil {
		t.Fatal("naming both Flux rows was accepted; the cluster would get two sets of controllers")
	}
	for _, want := range []string{FluxAIOName, FluxOperatorName, "a cluster gets one"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q does not contain %q", err, want)
		}
	}
	// Either one alone is a decision, not an error.
	for _, name := range []string{FluxAIOName, FluxOperatorName} {
		if err := (Request{Components: []string{name}}).Validate(); err != nil {
			t.Errorf("`kelson install %s` alone was refused: %v", name, err)
		}
	}
}

// TestFluxAIOAdoptsAnyFluxWhateverInstalledIt is ADR-0030 decision 1's other
// half. The single-pod shape is right for a cluster with no Flux and wrong as a
// migration for a cluster that has some, so this refusal is a design position,
// not bookkeeping.
func TestFluxAIOAdoptsAnyFluxWhateverInstalledIt(t *testing.T) {
	c, ok := Lookup(FluxAIOName)
	if !ok {
		t.Fatal("the pins table has no flux-aio row")
	}
	for _, tc := range []struct {
		name string
		prof clusterprofile.ClusterProfile
	}{
		{"flux-operator", clusterprofile.ClusterProfile{FluxOperator: &clusterprofile.Component{Version: "v0.58.0"}}},
		{"bootstrapped flux", clusterprofile.ClusterProfile{Flux: &clusterprofile.Component{Version: "2.9.1"}}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			outcome, reason := c.Presence(tc.prof)
			if outcome != clusterprofile.OutcomeYes {
				t.Fatalf("Presence() = %v, want yes: a cluster with Flux is adopted, whatever installed it",
					outcome)
			}
			if reason == "" {
				t.Fatal("the refusal says nothing about what was found")
			}
		})
	}
}
